require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NationsController do

  # This should return the minimal set of attributes required to create a valid
  # Nation. As you add validations to Nation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all nations as @nations" do
      nation = Nation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nations).should eq([nation])
    end
  end

  describe "GET show" do
    it "assigns the requested nation as @nation" do
      nation = Nation.create! valid_attributes
      get :show, {:id => nation.to_param}, valid_session
      assigns(:nation).should eq(nation)
    end
  end

  describe "GET new" do
    it "assigns a new nation as @nation" do
      get :new, {}, valid_session
      assigns(:nation).should be_a_new(Nation)
    end
  end

  describe "GET edit" do
    it "assigns the requested nation as @nation" do
      nation = Nation.create! valid_attributes
      get :edit, {:id => nation.to_param}, valid_session
      assigns(:nation).should eq(nation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Nation" do
        expect {
          post :create, {:nation => valid_attributes}, valid_session
        }.to change(Nation, :count).by(1)
      end

      it "assigns a newly created nation as @nation" do
        post :create, {:nation => valid_attributes}, valid_session
        assigns(:nation).should be_a(Nation)
        assigns(:nation).should be_persisted
      end

      it "redirects to the created nation" do
        post :create, {:nation => valid_attributes}, valid_session
        response.should redirect_to(Nation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nation as @nation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nation.any_instance.stub(:save).and_return(false)
        post :create, {:nation => { "name" => "invalid value" }}, valid_session
        assigns(:nation).should be_a_new(Nation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nation.any_instance.stub(:save).and_return(false)
        post :create, {:nation => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nation" do
        nation = Nation.create! valid_attributes
        # Assuming there are no other nations in the database, this
        # specifies that the Nation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Nation.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => nation.to_param, :nation => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested nation as @nation" do
        nation = Nation.create! valid_attributes
        put :update, {:id => nation.to_param, :nation => valid_attributes}, valid_session
        assigns(:nation).should eq(nation)
      end

      it "redirects to the nation" do
        nation = Nation.create! valid_attributes
        put :update, {:id => nation.to_param, :nation => valid_attributes}, valid_session
        response.should redirect_to(nation)
      end
    end

    describe "with invalid params" do
      it "assigns the nation as @nation" do
        nation = Nation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nation.any_instance.stub(:save).and_return(false)
        put :update, {:id => nation.to_param, :nation => { "name" => "invalid value" }}, valid_session
        assigns(:nation).should eq(nation)
      end

      it "re-renders the 'edit' template" do
        nation = Nation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nation.any_instance.stub(:save).and_return(false)
        put :update, {:id => nation.to_param, :nation => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nation" do
      nation = Nation.create! valid_attributes
      expect {
        delete :destroy, {:id => nation.to_param}, valid_session
      }.to change(Nation, :count).by(-1)
    end

    it "redirects to the nations list" do
      nation = Nation.create! valid_attributes
      delete :destroy, {:id => nation.to_param}, valid_session
      response.should redirect_to(nations_url)
    end
  end

end
