require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OfficialAdministratorsController do

  # This should return the minimal set of attributes required to create a valid
  # OfficialAdministrator. As you add validations to OfficialAdministrator, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "official_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OfficialAdministratorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all official_administrators as @official_administrators" do
      official_administrator = OfficialAdministrator.create! valid_attributes
      get :index, {}, valid_session
      assigns(:official_administrators).should eq([official_administrator])
    end
  end

  describe "GET show" do
    it "assigns the requested official_administrator as @official_administrator" do
      official_administrator = OfficialAdministrator.create! valid_attributes
      get :show, {:id => official_administrator.to_param}, valid_session
      assigns(:official_administrator).should eq(official_administrator)
    end
  end

  describe "GET new" do
    it "assigns a new official_administrator as @official_administrator" do
      get :new, {}, valid_session
      assigns(:official_administrator).should be_a_new(OfficialAdministrator)
    end
  end

  describe "GET edit" do
    it "assigns the requested official_administrator as @official_administrator" do
      official_administrator = OfficialAdministrator.create! valid_attributes
      get :edit, {:id => official_administrator.to_param}, valid_session
      assigns(:official_administrator).should eq(official_administrator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OfficialAdministrator" do
        expect {
          post :create, {:official_administrator => valid_attributes}, valid_session
        }.to change(OfficialAdministrator, :count).by(1)
      end

      it "assigns a newly created official_administrator as @official_administrator" do
        post :create, {:official_administrator => valid_attributes}, valid_session
        assigns(:official_administrator).should be_a(OfficialAdministrator)
        assigns(:official_administrator).should be_persisted
      end

      it "redirects to the created official_administrator" do
        post :create, {:official_administrator => valid_attributes}, valid_session
        response.should redirect_to(OfficialAdministrator.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved official_administrator as @official_administrator" do
        # Trigger the behavior that occurs when invalid params are submitted
        OfficialAdministrator.any_instance.stub(:save).and_return(false)
        post :create, {:official_administrator => { "official_id" => "invalid value" }}, valid_session
        assigns(:official_administrator).should be_a_new(OfficialAdministrator)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OfficialAdministrator.any_instance.stub(:save).and_return(false)
        post :create, {:official_administrator => { "official_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested official_administrator" do
        official_administrator = OfficialAdministrator.create! valid_attributes
        # Assuming there are no other official_administrators in the database, this
        # specifies that the OfficialAdministrator created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OfficialAdministrator.any_instance.should_receive(:update_attributes).with({ "official_id" => "1" })
        put :update, {:id => official_administrator.to_param, :official_administrator => { "official_id" => "1" }}, valid_session
      end

      it "assigns the requested official_administrator as @official_administrator" do
        official_administrator = OfficialAdministrator.create! valid_attributes
        put :update, {:id => official_administrator.to_param, :official_administrator => valid_attributes}, valid_session
        assigns(:official_administrator).should eq(official_administrator)
      end

      it "redirects to the official_administrator" do
        official_administrator = OfficialAdministrator.create! valid_attributes
        put :update, {:id => official_administrator.to_param, :official_administrator => valid_attributes}, valid_session
        response.should redirect_to(official_administrator)
      end
    end

    describe "with invalid params" do
      it "assigns the official_administrator as @official_administrator" do
        official_administrator = OfficialAdministrator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OfficialAdministrator.any_instance.stub(:save).and_return(false)
        put :update, {:id => official_administrator.to_param, :official_administrator => { "official_id" => "invalid value" }}, valid_session
        assigns(:official_administrator).should eq(official_administrator)
      end

      it "re-renders the 'edit' template" do
        official_administrator = OfficialAdministrator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OfficialAdministrator.any_instance.stub(:save).and_return(false)
        put :update, {:id => official_administrator.to_param, :official_administrator => { "official_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested official_administrator" do
      official_administrator = OfficialAdministrator.create! valid_attributes
      expect {
        delete :destroy, {:id => official_administrator.to_param}, valid_session
      }.to change(OfficialAdministrator, :count).by(-1)
    end

    it "redirects to the official_administrators list" do
      official_administrator = OfficialAdministrator.create! valid_attributes
      delete :destroy, {:id => official_administrator.to_param}, valid_session
      response.should redirect_to(official_administrators_url)
    end
  end

end
