require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StateSenateDistrictsController do

  # This should return the minimal set of attributes required to create a valid
  # StateSenateDistrict. As you add validations to StateSenateDistrict, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "district_number" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StateSenateDistrictsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all state_senate_districts as @state_senate_districts" do
      state_senate_district = StateSenateDistrict.create! valid_attributes
      get :index, {}, valid_session
      assigns(:state_senate_districts).should eq([state_senate_district])
    end
  end

  describe "GET show" do
    it "assigns the requested state_senate_district as @state_senate_district" do
      state_senate_district = StateSenateDistrict.create! valid_attributes
      get :show, {:id => state_senate_district.to_param}, valid_session
      assigns(:state_senate_district).should eq(state_senate_district)
    end
  end

  describe "GET new" do
    it "assigns a new state_senate_district as @state_senate_district" do
      get :new, {}, valid_session
      assigns(:state_senate_district).should be_a_new(StateSenateDistrict)
    end
  end

  describe "GET edit" do
    it "assigns the requested state_senate_district as @state_senate_district" do
      state_senate_district = StateSenateDistrict.create! valid_attributes
      get :edit, {:id => state_senate_district.to_param}, valid_session
      assigns(:state_senate_district).should eq(state_senate_district)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StateSenateDistrict" do
        expect {
          post :create, {:state_senate_district => valid_attributes}, valid_session
        }.to change(StateSenateDistrict, :count).by(1)
      end

      it "assigns a newly created state_senate_district as @state_senate_district" do
        post :create, {:state_senate_district => valid_attributes}, valid_session
        assigns(:state_senate_district).should be_a(StateSenateDistrict)
        assigns(:state_senate_district).should be_persisted
      end

      it "redirects to the created state_senate_district" do
        post :create, {:state_senate_district => valid_attributes}, valid_session
        response.should redirect_to(StateSenateDistrict.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved state_senate_district as @state_senate_district" do
        # Trigger the behavior that occurs when invalid params are submitted
        StateSenateDistrict.any_instance.stub(:save).and_return(false)
        post :create, {:state_senate_district => { "district_number" => "invalid value" }}, valid_session
        assigns(:state_senate_district).should be_a_new(StateSenateDistrict)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StateSenateDistrict.any_instance.stub(:save).and_return(false)
        post :create, {:state_senate_district => { "district_number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested state_senate_district" do
        state_senate_district = StateSenateDistrict.create! valid_attributes
        # Assuming there are no other state_senate_districts in the database, this
        # specifies that the StateSenateDistrict created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StateSenateDistrict.any_instance.should_receive(:update_attributes).with({ "district_number" => "1" })
        put :update, {:id => state_senate_district.to_param, :state_senate_district => { "district_number" => "1" }}, valid_session
      end

      it "assigns the requested state_senate_district as @state_senate_district" do
        state_senate_district = StateSenateDistrict.create! valid_attributes
        put :update, {:id => state_senate_district.to_param, :state_senate_district => valid_attributes}, valid_session
        assigns(:state_senate_district).should eq(state_senate_district)
      end

      it "redirects to the state_senate_district" do
        state_senate_district = StateSenateDistrict.create! valid_attributes
        put :update, {:id => state_senate_district.to_param, :state_senate_district => valid_attributes}, valid_session
        response.should redirect_to(state_senate_district)
      end
    end

    describe "with invalid params" do
      it "assigns the state_senate_district as @state_senate_district" do
        state_senate_district = StateSenateDistrict.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StateSenateDistrict.any_instance.stub(:save).and_return(false)
        put :update, {:id => state_senate_district.to_param, :state_senate_district => { "district_number" => "invalid value" }}, valid_session
        assigns(:state_senate_district).should eq(state_senate_district)
      end

      it "re-renders the 'edit' template" do
        state_senate_district = StateSenateDistrict.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StateSenateDistrict.any_instance.stub(:save).and_return(false)
        put :update, {:id => state_senate_district.to_param, :state_senate_district => { "district_number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested state_senate_district" do
      state_senate_district = StateSenateDistrict.create! valid_attributes
      expect {
        delete :destroy, {:id => state_senate_district.to_param}, valid_session
      }.to change(StateSenateDistrict, :count).by(-1)
    end

    it "redirects to the state_senate_districts list" do
      state_senate_district = StateSenateDistrict.create! valid_attributes
      delete :destroy, {:id => state_senate_district.to_param}, valid_session
      response.should redirect_to(state_senate_districts_url)
    end
  end

end
